### ISSUE TITLE
check/implement a proper flexlink generation

### ISSUE THREAD

**Issue by zirnipa** [mpay24/mpay24-php#14]
It seems that the flexlink generation does not work proper. 

We should have a look on that.
Also we should add the new parameter (profiles, validtill,...)

**Comment by stefanpolzer** [comment]
I believe you have a Semantic Error in the Code. I refer now to Commit https://github.com/mpay24/mpay24-php/commit/0739597ce940211f7901d906aa27f81963a7cc9e but this was already in the previous Master Branch. Look at Line 164 and 168. Dose two variables are never declared. Maybe this is the  cause for this issue

**Comment by stefanpolzer** [comment]
@tobiaslins could I have a test account for felx link integration? I belive I found a bug on this...

**Comment by stefanpolzer** [comment]
@zirnipa Is there a doc where I can find the possible parameters? It would be cool if we could fix this in the next major release.

**Comment by zirnipa** [comment]
We can remove all flexlink parts from the SDK, since it is not supported anymore (business decision).

**Comment by stefanpolzer** [comment]
@zirnipa I will do this in my 5.0.0 PR #90 @mdaskalov can you mark all methods in the `Mpay24FlexLink` and all related Methods in `Mpay24Config` and `Mpay24Sdk` as deprecated as of 5.0.0, but keep the functionality for 4.x?

**Comment by stefanpolzer** [comment]
@zirnipa I assume you can close this one now. Flexlink implement is removed in PR #90
