### ISSUE TITLE
PHP Basic syntax

### ISSUE THREAD

**Issue by stefanpolzer** [mpay24/mpay24-php#17]
Its not a big deal but somtimes it can lead to a HTTP response, before the header is send and this leads to an Error.
I would recomand to use the PHP Tags as recomandet by PHP it self:
> If a file is pure PHP code, it is preferable to omit the PHP closing tag at the end of the file. 

[http://php.net/manual/en/language.basic-syntax.phptags.php](http://php.net/manual/en/language.basic-syntax.phptags.php)

**Comment by tobiaslins** [comment]
So you would recommend to remove all closing tags in `MPAY24.php`, `MPAY24SDK.php`, `orderXML.php` and `config.php` ?

**Comment by stefanpolzer** [comment]
Yes

**Comment by stefanpolzer** [comment]
Is now fixed in the psr-4 branch
