### ISSUE TITLE
PSR4 Compliance

### ISSUE THREAD

**Issue by stefanpolzer** [mpay24/mpay24-php#20]
As mentioned in the PSR-4 Documentation 2.3.3 

> The terminating class name corresponds to a file name ending in .php. The file name MUST match the case of the terminating class name.

You have 3 Classes in the MPAY24.php file and 7 Classes in the MPAY24SDK.php file.
Im not sure if those are only private classes but if not thay MUST be refactored to a seperat class.

I would recomand:
```
lib/MPAY24/MPAY24.php
lib/MPAY24/Transaction.php
lib/MPAY24/MPay24flexLINK.php
lib/MPAY24SDK/MPAY24SDK.php
lib/MPAY24SDK/GeneralResponse.php
lib/MPAY24SDK/PaymentResponse.php
lib/MPAY24SDK/PaymentTokenResponse.php
lib/MPAY24SDK/ManagePaymentResponse.php
lib/MPAY24SDK/ListPaymentMethodsResponse.php
lib/MPAY24SDK/TransactionStatusResponse.php
lib/Order/OrderXML.php
```
[http://www.php-fig.org/psr/psr-4/](http://www.php-fig.org/psr/psr-4/)

**Comment by tobiaslins** [comment]
Hi, 
@stefanpolzer already implemented the PSR4 compliance into our branch.
Please check the psr4 branch - #23

**Comment by stefanpolzer** [comment]
I will test it. BTW Commit https://github.com/mpay24/mpay24-php/commit/1d7dbe327801b1cc1dfabf68d8a643e15c6f2d89 is only in Master branch

**Comment by stefanpolzer** [comment]
Looks good to me....
