### ISSUE TITLE
Missing requirements in composer.json file

### ISSUE THREAD

**Issue by stefanpolzer** [mpay24/mpay24-php#21]
Your package have 4 PHP requirements but only one is listed in the composer.json: "php": ">=5.3.3"
For better UX I request to add the others as well:
```
"ext-curl": "*",
"ext-dom": "*",
"ext-mcrypt": "*"
```

**Comment by tobiaslins** [comment]
thanks!

**Comment by wumeihk** [comment]
it solved my problem!thanks!
