### ISSUE TITLE
ErrorException wile running MPAY24 in PHP CLI

### ISSUE THREAD

**Issue by stefanpolzer** [mpay24/mpay24-php#27]
Encounter a problem while running in PHP CLI!

I plan to run a cron job that will check for Subscriptions that must be renewed and than calling acceptPayment() on a MPAY24 Object.

The Problem is that this cause the following exception:

`exception 'ErrorException' with message 'Undefined index: SERVER_NAME' in \vendor\mpay24\mpay24-php\lib\MPAY24.php:171`

Reason is very simple $_SERVER['SERVER_NAME'] is not set in PHP CLI
This will only be set by a Web-server but not in CLI

**Comment by tobiaslins** [comment]
we should replace this and use [php_uname](http://stackoverflow.com/questions/626416/php-server-name-from-command-line) instead
