### ISSUE TITLE
Any plans for PHPUnit Test's

### ISSUE THREAD

**Issue by stefanpolzer** [mpay24/mpay24-php#34]
The most resend changes should show that it s very hard to develop some features if, no tests are available.
Because we are needing the interface on the mPAY24 Server as well that makes it a little bit more difficult.

I'm very customer oriented but I don't know all possible features that are currently supported and,
I don't know also what are the general rule of thumb in your organization how you handle backward compatibility.

Having test cases that must run successful, would make it eraser to see if changes may break things.

Do you see any changes to have some of those Test Cases?

**Comment by tobiaslins** [comment]
We currently don't have plans for PHPUnit tests. Unit tests would be great - but they are currently not on our plan!

**Comment by stefanpolzer** [comment]
@mdaskalov since PR #85 we have the firsts Unit test include, even if the coverage is very low. I try to add some real world test cases while I'm working on some Projects but I can't write all. I assume we can close this one after PR #90 is merged, where I add some more test cases. It would be nice if some people could help to add some more test cases so we get a higher coverage over the time.

**Comment by stefanpolzer** [comment]
PHPUnit Test is now implementet see PR #90.
