### ISSUE TITLE
AcceptPayment Request with Token =>  Order description can't be set

### ISSUE THREAD

**Issue by stefanpolzer** [mpay24/mpay24-php#35]
Hi, I did not find the right dokumenation for setting the Order description in a AcceptPayment Request with Token.
It's documented in https://www.mpay24.com/soap/etp/1.5/ETP.wsdl

I refer also to this: https://docs.mpay24.com/docs/tokenizer-integration
especially to:
```
      <order>
        <description>Example payment</description>
      </order>
```
I also do not see any way to do it with the current implementation

**Comment by tobiaslins** [comment]
Currently setting the description is not possible with our php sdk.
The problem is that we don't have a method that transforms a php array into a `DOMDocument`

It would be great if we could support:
```php
  $additional = array(
    "order" => array(
       "description" => "Example payment"
     )
  );
```

At the moment only key value is possible (no multiple dimensions)

**Comment by stefanpolzer** [comment]
Ok If its not implemented I don't have to search...
But this is a good stating point.... This should not be to difficult to be done
