### ISSUE TITLE
PSR1 & PSR2

### ISSUE THREAD

**Issue by stefanpolzer** [mpay24/mpay24-php#40]
Having the PSR-4 Branch almost ready rises the question about
[PSR1](http://www.php-fig.org/psr/psr-1/) (Basic Coding Standard) & [PSR2](http://www.php-fig.org/psr/psr-2/) (Coding Style Guide)

Some of the rules are already realized some are not. From PSR 1:
- Class names MUST be declared in `StudlyCaps`.
- Method names MUST be declared in `camelCase`

For PSR 2 the are also a view things that could be improved:
- Code MUST use 4 spaces for indenting, not tabs.
- Visibility MUST be declared on all properties and methods;
- Opening parentheses for control structures MUST NOT have a space after them, and closing parentheses for control structures MUST NOT have a space before.

Most of this can be done with the IDE and on Keystrok,
but the names for Classes in `StudlyCaps` and Method names in `camelCase` needs manuel changes.

My suggestion is to change it!

If you have any concerns about the MPAY24 class than we could build a wrapper class with this name and declarer it as deprecated, and remove it in the Next Major Update
This gives you also time to update the documentation accordingly

A good solution IMHO would be: namspace = Mpay24
Class names are:

Mpay24 or Better Mpay24Soap
Mpay24Config
Mpay24FlexLink
Mpay24Sdk
Order or Better Mpay24Order

every other Class Name is alright
All methods will be changed to `camelCase`

If you agree with it, I could create a pull request.

In the WIKI or somewhere else you could do a article where you declare that you code MUST be written according to dose PSR1 & PSR2 & PRS4 Standards, this makes it easier for every one ho wants to contribute.

**Comment by tobiaslins** [comment]
@stefanpolzer you are pretty fast :)
I just merged your PR, but sadly found afterwards one thing I want to change.
In fact our transaction status can be used by mpaytid (this is the name of the variable for each transaction)
You renamed the function transactionStatusByMpayTid to transactionStatusByMpay24Tid

In my opinion it would be much more clear to rename this function back and keep the `Mpaytid` for all cases with this variable!

**Comment by stefanpolzer** [comment]
@tobiaslins I was renaming any thing to `Mpay24` so yes in this case because it is also in the backen called mPAYTID I absolutely agree to rename it back to `transactionStatusByMpayTid()`.  Makes more sense.

As far as I understand there are 3 Method to interact with the mPAY24 Server

1. SOAP
2. HTML
3. FlexLink (that is maybe a part of HTML)

so having having Calsse Called Mpay24Soap, Mpay24FlexLink and maybe on Day `Mpay24Html' makes more sense to me than just 'MPAY24'.

Class Names should not interfere with REST rules, what do you mean?

**Comment by tobiaslins** [comment]
@stefanpolzer 
Check out the latest commit https://github.com/mpay24/mpay24-php/commit/9dbee6417030503fb999b65aab883d123fcbe4fc

We will stay on the class name `Mpay24` for now!

Also it is now only possible to capture, refund and cancel transactions by `mPAYTID` instead of `tid`

The payment status can now be send with `paymentStatus` request which takes also the mpaytid
If someone wants to get the status by tid, he should use `paymentStatusByTid`

**Comment by stefanpolzer** [comment]
@tobiaslins if you want to stick with Mpay24 it is OK for me. It was just a proposal.
Using mPAYTID in favor of tid is a good idea ;-)

I will update some PHPdocs in a minute
