### ISSUE TITLE
Callback Validation fails although callback is valid

### ISSUE THREAD

**Issue by jolicht** [mpay24/mpay24-php#56]
expression of key **BRAND** of class constant **CONFIRMATION_PROPERTIES** of class **Mpay24\Mpay24Confirmation** should contain string **PAYPAL** as validation fails, if paypal-payment is used.

**Comment by stefanpolzer** [comment]
Can you provide a request and the associated responses (The confirmation URL query parameter string)?

To my understanding the BRAND=PAYPAL is invalid.
According to all SOAP API docs, BRAND is a enumeration
https://docs.mpay24.com/v1.5/docs/payment-notification#section-notification-values
The Push method is the main us-case for the Mpay24Confirmation class.

You can find the specification for the enumeration BRAND for example here:
https://docs.mpay24.com/v1.5/docs/backend2backend-integration#section-payment-system-integration

With Paypal the pType = PAYPAL but the BRAND = n/a
So BRAND should be empty in the request and also in the confirmation response.

**Comment by jolicht** [comment]
I create an order and specifiy payment type and do not set the brand:
`$mpay24Order->Order->PaymentTypes->Payment(1)->setType("PAYPAL");`

Redirect URL for Checkout page is https://test.mpay24.com/app/bin/checkout/payment/[some hash]

mpay24 confirmation url call:

`http://localhost:8080/api/v1/de-AT/payment/callback/paypal/?uuid=ed986f9a-7f93-4f23-af5a-d13e2cea300e&OPERATION=CONFIRMATION&TID=BNW15907403&STATUS=BILLED&PRICE=2380&CURRENCY=EUR&P_TYPE=PAYPAL&BRAND=PAYPAL&MPAYTID=3903833&USER_FIELD=&ORDERDESC=&CUSTOMER=BNW15907403&CUSTOMER_EMAIL=&LANGUAGE=DE&CUSTOMER_ID=&PROFILE_ID=&PROFILE_STATUS=IGNORED&FILTER_STATUS=&APPR_CODE=8EC95924TV260551G
`

i do not set brand but it's query part of mpays confirmation url call. And as brand PAYPAL isn't allowed, validation fails.

**Comment by stefanpolzer** [comment]
@tobiaslins did the callback URL logic change in the last time?
Why is all the documentation saying that in PAYPAL context BRAND is n/a but as in @jolicht example it is send?

Is the documentation wrong or not up to date?
If so we have to change the logic .... can you provide a up-to-date list of valid BRAND Strings...
I can update the Mpay24Confirmation Class if needed....

**Comment by tobiaslins** [comment]
@stefanpolzer @jolicht 
I think our documentation does not cover this completely.
If there are no sub brands from a payment type we usually send the same brand as the p_type.
This means that we will return `P_TYPE=PAYPAL` and `BRAND=PAYPAL`

There are two options to solve this
* We add all missing `BRAND` constants (each where n/a in documentation)
* We create an additional constant array for all these `P_TYPE`s and then just ignore in these cases the `BRAND`

Do you have another ideas?

**Comment by stefanpolzer** [comment]
The class have no logic at the moment, so I provide just a quick fix by adding all the missing n/a `BRAND` constants.

**Comment by tobiaslins** [comment]
Thank you!

Quickfix available in release [4.0.2](https://github.com/mpay24/mpay24-php/releases/tag/4.0.2)
