### ISSUE TITLE
PHP Version 5.3.8 - Parse error: syntax error, unexpected '['

### ISSUE THREAD

**Issue by zirnipa** [mpay24/mpay24-php#58]
Tested our SDK with PHP Version 5.3.8:
It looks like this PHP version does not support the used array declaration

public function token($paymentType, array $additional = [])
public function createTokenPayment($pType, array $additional = [])
public function acceptPayment($type, $tid, $payment = [], $additional = [])

Parse error: syntax error, unexpected '[' in C:\xampp\htdocs\sdk\src\Mpay24.php on line 189

I think we should only support the supported versions: http://php.net/supported-versions.php

**Comment by stefanpolzer** [comment]
You right this annotation is only supported in PHP 5.4+.... I also agree that only the new PHP Version should be supported, this old PHP version are also a kind of security risk.

**Comment by chesio** [comment]
The SDK as it is requires PHP 5.6 at least, see: https://github.com/mpay24/mpay24-php/blob/master/src/Mpay24Confirmation.php#L42-L61

```php
const CONFIRMATION_PROPERTIES = [
    'OPERATION'      => 'CONFIRMATION',
    'TID'            => '.{0,32}',
    ...
```

From [PHP manual](https://secure.php.net/manual/en/language.constants.syntax.php):

> As of PHP 5.6 it is possible to define array constant using const keywords [...]

**Comment by stefanpolzer** [comment]
@zirnipa I assume this on is now obsolete or do we need a fix on the older version 4.x for PHP 5.3.8?
