### ISSUE TITLE
On payment error no mpaytid

### ISSUE THREAD

**Issue by zirnipa** [mpay24/mpay24-php#64]
If a payment fails (e.g. using expiry month 01-04 on testsystem), getMpayTid() returns no mpaytid.

echo "ReturnCode: " . $result->getReturnCode();
echo "<br>";
echo "mPAYTID: " . $result->getMpayTid();

->

ReturnCode: EXTERNAL_ERROR
mPAYTID: 
------

<etp:AcceptPaymentResponse xmlns:etp="https://www.mpay24.com/soap/etp/1.5/ETP.wsdl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="etp:AcceptPaymentResponse">
  <status>ERROR</status>
  <returnCode>EXTERNAL_ERROR</returnCode>
  <mpayTID>4100597</mpayTID>
  <errNo>100</errNo>
  <errText>Karte abgelaufen (card expired)</errText>
</etp:AcceptPaymentResponse>

----

For successful transactions getMpayTid() returns a valid mpaytid.

**Comment by stefanpolzer** [comment]
@zirnipa can you check if this is now solved in the last PR #90 that was now merged into the master tree?

**Comment by mdaskalov** [comment]
Solved in v5.0.0 with (PR #90)!
