### ISSUE TITLE
Exception: The schema you have created is not valid! Element 'ShoppingCart': This element is not expected. 

### ISSUE THREAD

**Issue by flashworks** [mpay24/mpay24-php#65]
https://docs.mpay24.com/docs/working-with-the-mpay24-php-sdk-redirect-integration

when trying to add a ShoppingCard item like displayed above under "Display a shoppingcart on the Payment Page" i get the following error:

> Exception: The schema you have created is not valid! Element 'ShoppingCart': This element is not expected. Expected is one of ( Customer, BillingAddr, ShippingAddr, URL )

the XML looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<Order>
 <Tid>[tid]</Tid>
 <Price>[price]</Price>
 <Currency>EUR</Currency>
 <ShoppingCart>
  <Item>
   <Number>1</Number>
   <ProductNr>[prod_nr]</ProductNr>
   <Description>[descr]</Description>
   <Quantity>1</Quantity>
   <ItemPrice Tax="2.30">12.30</ItemPrice>
   <Price>12.30</Price> 
  </Item>
  </ShoppingCart>
  <URL>
   <Success>[success_url]</Success>
   <Error>[error_url]</Error>
   <Confirmation>[confirmation_url]</Confirmation>
   <Cancel>[cancel_url]</Cancel>  
  </URL>
 </Order>
```

**Comment by tobiaslins** [comment]
The problem is, that the order of the elements is not correct.
Price and Currency should be after ShoppingCart!

You can find the correct order and more details [here](https://docs.mpay24.com/docs/mdxi-xml#section-order)

**Comment by flashworks** [comment]
works like a charm, thanks!
