### ISSUE TITLE
Syntax error in Mpay24Sdk.php:124

### ISSUE THREAD

**Issue by passioncoder** [mpay24/mpay24-php#70]
Please remove the trailing comma, it breaks the whole sdk:
https://github.com/mpay24/mpay24-php/blob/76387a9a692a4ec7a1ef303d4b66033a8dc3b280/src/Mpay24Sdk.php#L124

**Comment by tobiaslins** [comment]
Thank you for reporting @passioncoder ! 
It is fixed within version 4.2.2 (and already available on composer)

**Comment by passioncoder** [comment]
@tobiaslins thx!
