### ISSUE TITLE
Mpay24Order.php __set() preg_match to strict

### ISSUE THREAD

**Issue by soeurdefeo** [mpay24/mpay24-php#86]
https://github.com/mpay24/mpay24-php/blob/1b38315ae3df610f7cdd85312152f3505dab1848/src/Mpay24Order.php#L179

This preg_match breaks strings like descriptions with numbers that matches the pattern.

Tested with `ShoppingCart->Item( $item_key )->Description = "10,00 € fee"`
**False Result:** 10.00

Requirement: preg_match should not replace attributes / values that are defined as strings in MDXI.xsd (a) or should at least not trim string after matching substring (b).
**True Result (a):** 10,00 € fee
**True Result (b):** 10.00 € fee

**Comment by stefanpolzer** [comment]
@soeurdefeo can you check if this is now solved in the last PR #90 that was now merged into the master tree?

**Comment by mdaskalov** [comment]
fixed in v5.0.0 (#90)
