### ISSUE TITLE
Throw exception instead of using die()

### ISSUE THREAD

**Issue by TheLevti** [mpay24/mpay24-php#92]
Could you please throw exceptions instead of using die(), terminating the whole script?

This practice is quite counter productive when using your library with a framework or in console commands.

There are several places in the code where `die('Some reason.')` is used.

- Mpay24.php
- Mpay24FlexLink.php
- Mpay24Order.php

**Comment by stefanpolzer** [comment]
+1

**Comment by stefanpolzer** [comment]
@zirnipa this is now implemented/changed in #90, we can close it now.
