### ISSUE TITLE
Make the code more robust

### ISSUE THREAD

**Issue by szepeviktor** [mpay24/mpay24-php#93]
Please consider introducing @phpstan as it has great benefits.

I could help as much as necessary.

It is easy to start: `phpstan analyze -l 2 src/`
phpstan may have problmes with DOMNode class - still there are a lot of benefits!

**Comment by stefanpolzer** [comment]
@zirnipa this is basically implemented now in #90
@szepeviktor you are welcome to enhance the code to get a higer validation level.

**Comment by zirnipa** [comment]
I am closing the ticket for now.

**Comment by szepeviktor** [comment]
Okay.
